id: P004236
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24782
  title: རྣམ་འགྲེལ་མཐའ་དཔྱོད་ཀྱི་མཆན་འགྲེལ་ཀུན་མཁྱེན་ཞལ་ལུང་།
  author: ''
  volumes:
    caae8938c26c4b70b42bf5405e0e2923:
      image_group_id: I1KG24784
      title: ''
      volume_number: 1
      total_pages: 103
      base_file: v001.txt
